### PR TITLE
Terminal initialisation

### LINKED ISSUE #1: Initiate the "front" project

### PR DESCRIPTION
**Pull request by MansourWolou**
The mobile app is initialised
Contributin.md define contribution process

Closes #1

### CODE REVIEW

**Review by MelvinCou — COMMENTED** [review]
Edit root README.md with commands to launch project and flutter/dart version.

**Review by MelvinCou — COMMENTED** [review]
Fix dependencies, some are not up to date / useless:

```sh
❯ flutter pub get
Resolving dependencies... (1.5s)
> collection 1.17.2 (was 1.17.1) (1.18.0 available)
  flutter_lints 2.0.3 (3.0.1 available)
  lints 2.1.1 (3.0.0 available)
> matcher 0.12.16 (was 0.12.15)
> material_color_utilities 0.5.0 (was 0.2.0) (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
> source_span 1.10.0 (was 1.9.1)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
> test_api 0.6.0 (was 0.5.1) (0.6.1 available)
+ web 0.1.4-beta (0.4.0 available)
These packages are no longer being depended on:
- js 0.6.7
Changed 7 dependencies!
```

With the command:
```sh
flutter pub upgrade --major-versions
```

**Review by MeloLawson — APPROVED** [review]

**Review by MelvinCou — CHANGES_REQUESTED** [review]
Add `terminal/.dockerignore`  with:

- .dockerignore
- .gitignore
- README.md
- build
- Dockerfile

Run \\/ to update flutter_lints from 2.0.3 to 3.0.1

```sh
flutter pub upgrade --major-versions
```

**Review by PaulIRVOAS — CHANGES_REQUESTED** [review]
Please merge doc/4-wireframes branch into yours to get readme changement.

**Review by MelvinCou — APPROVED** [review]

**Review by PaulIRVOAS — APPROVED** [review]
approved

**Pull request merged**
